import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export function generateTokens(css: string): string {
  const declarations = (selector: string): Record<string, string> => {
    const start = css.indexOf(selector);
    if (start < 0) throw new Error(`Missing token scope ${selector}`);
    const body = css.slice(start + selector.length, css.indexOf('}', start));
    return Object.fromEntries([...body.matchAll(/(--wa-[\w-]+)\s*:\s*([^;]+);/g)]
      .map((match) => [match[1], match[2]?.trim().replace(/\s+/g, ' ')]));
  };
  const light = declarations(':root {');
  const darkOverrides = declarations(":root[data-theme='dark'] {");
  const osDark = declarations(":root:not([data-theme='light']) {");
  if (JSON.stringify(osDark) !== JSON.stringify(darkOverrides)) throw new Error('Dark scopes differ');
  const resolve = (values: Record<string, string>): Record<string, string> => {
    const value = (name: string, seen: readonly string[] = []): string => {
      if (seen.includes(name)) throw new Error(`Token cycle: ${name}`);
      const raw = values[name];
      if (raw === undefined) throw new Error(`Missing token: ${name}`);
      return raw.replace(/var\((--wa-[\w-]+)\)/g, (_, ref: string) => value(ref, [...seen, name]))
        .replace('var(--font-inter)', 'Inter');
    };
    return Object.fromEntries(Object.keys(values).sort().map((name) => [name, value(name)]));
  };
  return '// Generated by tokens:generate. Edit tokens.css, then regenerate.\n'
    + `// Source SHA-256: ${createHash('sha256').update(css).digest('hex')}\n`
    + `export const tokenValues = ${JSON.stringify({ light: resolve(light), dark: resolve({ ...light, ...darkOverrides }) }, null, 2)} as const;\n`
    + 'export type TokenName = keyof typeof tokenValues.light;\n'
    + 'export const tokenNames = Object.keys(tokenValues.light) as TokenName[];\n';
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(new URL('../src/tokens.generated.ts', import.meta.url),
    generateTokens(readFileSync(new URL('../src/tokens.css', import.meta.url), 'utf8')));
}
