import type { BuilderScreenData } from '../campaigns/load';
import { CampaignPage, DetailsTable, Notice, Badge } from '../campaigns/ui';
export default function EligibilityScreen({ data }: { data: BuilderScreenData }) {
  const ready = data.view === 'ready';
  const sources = [['Daily budget meets the marketplace minimum', 'A campaign that is rejected the moment it is sent', 'Marketplace rules', ready && data.context.budget !== null], ['Campaign name is not already in use', 'Two campaigns you cannot tell apart a month later', 'Campaign mirror', ready], ['Name matches your saved convention', 'A campaign the reverse builder cannot read back', 'Your naming preset', ready && data.context.naming !== null], ['Bid × placement multiplier stays under the ceiling', 'Paying far more per click than you intended', 'Your exposure ceiling', ready && data.context.exposureCeiling !== null], ['Ad type supports the control you set', 'Configuring something the ad type cannot do', 'Capability snapshot', ready], ['Product is in stock', 'Spending on a product that cannot be bought', 'Listing snapshots', false], ['Product holds the Buy Box', 'Ads that send traffic to someone else’s offer', 'Listing snapshots', false], ['Listing is not suppressed', 'A campaign pointed at a hidden listing', 'Listing snapshots', false], ['Creative is approved by Amazon', 'A campaign built around a video that cannot serve', 'Moderation status', false]] as const;
  return <CampaignPage title="Eligibility before creation" subtitle="Available checks and their sources. Save a draft to validate its exact values.">
    {!ready && <Notice>{data.message}</Notice>}<DetailsTable headings={['Check', 'What it prevents', 'Can we run it', 'Where it comes from']} rows={sources.map(([label, prevents, source, runnable]) => [label, prevents, <span className="campaign-check-chip" data-runnable={runnable} title={runnable ? 'This check can run. The draft has not yet been validated.' : 'This source is not measured.'}><Badge>{runnable ? 'yes' : 'not measured'}</Badge></span>, source])} />
    <Notice><strong>A check we cannot run is shown as unavailable, never as passed.</strong><p>The four checks marked not measured all wait on the same two things: a daily capture of the listing, and Amazon’s moderation verdict on each asset. Until those exist the builder will let you through, and will say plainly that it could not look. Creative eligibility is explained in full on the Creatives screen.</p></Notice><a href={ready ? `/campaigns?profile=${data.context.profile.id}` : '/campaigns'}>Return to builder</a>
  </CampaignPage>;
}
