import { expect, test } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { OPTIMIZATION_METHOD_CATALOGUE } from '@wizard-ads/core';
import { signIn } from './support/auth';
import { readState } from './support/fixture';

test('catalogue preserves all nine release states, identifiers and accessible information', async ({ page }) => {
  const state = await readState();
  await signIn(page, 'admin');
  await page.setViewportSize({ width: 1440, height: 1024 });
  await page.goto(`/settings/strategy?profile=${state.fixtureProfileId}`);
  await expect(page.getByRole('heading', { name: 'Optimization methods', exact: true })).toBeVisible();
  const table = page.getByRole('table').first();
  await expect(table.getByRole('row')).toHaveCount(10);
  for (const method of OPTIMIZATION_METHOD_CATALOGUE) await expect(table.getByRole('row').filter({ hasText: method.displayName })).toHaveCount(1);
  await expect(table.getByRole('cell', { name: 'Draft', exact: true })).toHaveCount(7);
  await expect(table.getByRole('cell', { name: 'Shadow only', exact: true })).toHaveCount(1);
  const folder = resolve('node_modules/.cache/playwright/wp269');
  await mkdir(folder, { recursive: true });
  await page.screenshot({ path: resolve(folder, 'methods-catalogue.png'), fullPage: true });
  await page.getByRole('link', { name: 'Method identifiers and formulas' }).click();
  await expect(page.locator('#identifiers').getByRole('row')).toHaveCount(10);
  await page.screenshot({ path: resolve(folder, 'methods-identifiers.png'), fullPage: true });
  const info = page.getByRole('button', { name: 'About SP placement efficiency' });
  await info.focus(); await page.keyboard.press('Enter');
  await expect(page.getByRole('dialog', { name: 'About SP placement efficiency' })).toContainText('Preview only. Sending is unavailable.');
  const popup = await page.getByRole('dialog', { name: 'About SP placement efficiency' }).boundingBox();
  expect(popup).not.toBeNull();
  expect(popup!.x).toBeGreaterThanOrEqual(0);
  expect(popup!.x + popup!.width).toBeLessThanOrEqual(1440);
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(1440);
  await page.screenshot({ path: resolve(folder, 'methods-popover.png'), fullPage: true });
  await page.keyboard.press('Escape'); await expect(info).toBeFocused();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await info.hover(); await expect(page.getByRole('dialog')).toHaveCount(1);
  await page.getByRole('dialog').hover(); await expect(page.getByRole('dialog')).toHaveCount(1);
  await page.goto(`/strategy?profile=${state.fixtureProfileId}`);
  await expect(page).toHaveURL(new RegExp(`/settings/strategy\\?profile=${state.fixtureProfileId}`));
});
