/**
 * Agency identity and role contracts. These values identify a verified server
 * caller; parsing an actor is never authentication or proof of membership.
 * Installation provisioning is separate from every organization role.
 */
import { z } from 'zod';
import { Uuid } from './primitives.js';

export const AuthenticatedIdentity = z.object({ userId: Uuid }).strict();
export type AuthenticatedIdentity = z.infer<typeof AuthenticatedIdentity>;

export const OrgActor = AuthenticatedIdentity.extend({ orgId: Uuid }).strict();
export type OrgActor = z.infer<typeof OrgActor>;

export const OrgRole = z.enum(['owner', 'admin', 'analyst', 'viewer']);
export type OrgRole = z.infer<typeof OrgRole>;

export const OrgCapability = z.enum([
  'read',
  'editTargets',
  'toggleSync',
  'manageConnection',
  'manageMembers',
  'triageFeedback',
  'exportBatches',
  'manageExperiments',
]);
export type OrgCapability = z.infer<typeof OrgCapability>;

/** One policy table for presentation, server composition and SQL policy tests. */
export const ORG_CAPABILITY_ROLES = {
  read: ['owner', 'admin', 'analyst', 'viewer'],
  editTargets: ['owner', 'admin', 'analyst'],
  toggleSync: ['owner', 'admin'],
  manageConnection: ['owner', 'admin'],
  manageMembers: ['owner', 'admin'],
  triageFeedback: ['owner', 'admin'],
  exportBatches: ['owner', 'admin'],
  manageExperiments: ['owner', 'admin', 'analyst'],
} as const satisfies Readonly<Record<OrgCapability, readonly OrgRole[]>>;

/** Team invitations cannot establish or transfer agency ownership. */
export const TeamInvitationRole = OrgRole.exclude(['owner']);
export type TeamInvitationRole = z.infer<typeof TeamInvitationRole>;

/** Server-to-database issuance; the raw invitation token is never stored. */
export const TeamInvitationIssue = z.object({
  email: z.email().max(320).trim().toLowerCase(),
  role: TeamInvitationRole,
  tokenHash: z.string().regex(/^[a-f0-9]{64}$/),
  tokenPrefix: z.string().regex(/^[A-Za-z0-9_-]{12}$/),
}).strict();
export type TeamInvitationIssue = z.infer<typeof TeamInvitationIssue>;

export const MemberRoleChange = z.object({ userId: Uuid, role: OrgRole }).strict();
export type MemberRoleChange = z.infer<typeof MemberRoleChange>;

/** Operator input only. No organization role grants installation authority. */
export const AgencyProvisionRequest = z.object({
  requestId: Uuid,
  name: z.string().trim().min(1).max(120),
  slug: z.string().min(2).max(63).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
  ownerEmail: z.string().trim().toLowerCase().pipe(z.email().max(320)),
}).strict();
export type AgencyProvisionRequest = z.infer<typeof AgencyProvisionRequest>;

/** Raw bearer tokens are generated by the operator and never stored in SQL. */
export const BootstrapTokenDigest = z.object({
  tokenHash: z.string().regex(/^[a-f0-9]{64}$/),
  tokenPrefix: z.string().regex(/^[A-Za-z0-9_-]{12}$/),
}).strict();
export type BootstrapTokenDigest = z.infer<typeof BootstrapTokenDigest>;

export const AgencyProvisionCommand = AgencyProvisionRequest.extend({ token: BootstrapTokenDigest });
export type AgencyProvisionCommand = z.infer<typeof AgencyProvisionCommand>;

export const BootstrapReissueCommand = z.object({
  requestId: Uuid,
  expectedGeneration: z.number().int().min(1).max(2_147_483_646),
  token: BootstrapTokenDigest,
}).strict();
export type BootstrapReissueCommand = z.infer<typeof BootstrapReissueCommand>;

export const BootstrapInvitationState = z.enum(['pending', 'expired', 'revoked', 'accepted']);
export type BootstrapInvitationState = z.infer<typeof BootstrapInvitationState>;

/** A retry never implies that an unknown original bearer token can be recovered. */
export const AgencyProvisionReceipt = z.object({
  requestId: Uuid,
  orgId: Uuid,
  invitationId: Uuid,
  generation: z.number().int().positive(),
  state: BootstrapInvitationState,
  outcome: z.enum(['created', 'existing', 'reissued']),
  tokenMatches: z.boolean(),
}).strict();
export type AgencyProvisionReceipt = z.infer<typeof AgencyProvisionReceipt>;

/** Acceptance selects the saved organization; clients cannot submit a role/org. */
export const BootstrapAcceptanceReceipt = z.object({
  orgId: Uuid,
  invitationId: Uuid,
  generation: z.number().int().positive(),
  outcome: z.enum(['accepted', 'already_accepted']),
}).strict();
export type BootstrapAcceptanceReceipt = z.infer<typeof BootstrapAcceptanceReceipt>;

/** Bearer-link inspection reveals only the invitation's recipient and agency. */
export const BootstrapInvitationView = z.object({
  agencyName: z.string(),
  ownerEmail: z.email(),
  generation: z.number().int().positive(),
  state: BootstrapInvitationState,
}).strict();
export type BootstrapInvitationView = z.infer<typeof BootstrapInvitationView>;

export const BootstrapRevokeCommand = z.object({
  requestId: Uuid,
  expectedGeneration: z.number().int().min(1).max(2_147_483_647),
}).strict();
export type BootstrapRevokeCommand = z.infer<typeof BootstrapRevokeCommand>;
