import { boolean, foreignKey, index, integer, jsonb, pgTable, primaryKey, text, uniqueIndex, uuid } from 'drizzle-orm/pg-core';
import { ts } from './columns.js';
import { adProduct, entityType } from './enums.js';
import { adProfiles, orgs } from './tenancy.js';

const tenant = { orgId: uuid('org_id').notNull().references(() => orgs.id, { onDelete: 'cascade' }), profileId: uuid('profile_id').notNull() };
export const adsCatalogueSourceSettings = pgTable('ads_catalogue_source_settings', { ...tenant, marketplaceId: text('marketplace_id').notNull(), family: text('family').notNull(), enabled: boolean('enabled').notNull().default(false), reportingRecoveryVerifiedAt: ts('reporting_recovery_verified_at'), updatedAt: ts('updated_at').notNull() }, (t) => [primaryKey({ columns: [t.profileId,t.marketplaceId,t.family] }), foreignKey({ columns: [t.orgId,t.profileId], foreignColumns: [adProfiles.orgId,adProfiles.id] }).onDelete('cascade')]);
export const adsCatalogueSourceReceipts = pgTable('ads_catalogue_source_receipts', { id: uuid('id').primaryKey(), ...tenant, marketplaceId: text('marketplace_id').notNull(), family: text('family').notNull(), selectorKey: text('selector_key').notNull(), windowStart: ts('window_start').notNull(), windowEnd: ts('window_end').notNull(), acquiredAt: ts('acquired_at').notNull(), completedAt: ts('completed_at').notNull(), counts: jsonb('counts').notNull(), pageCount: integer('page_count').notNull(), finalCursor: text('final_cursor'), collectionFingerprint: text('collection_fingerprint').notNull(), acquisitionKey:text('acquisition_key').notNull() }, (t) => [foreignKey({ columns: [t.orgId,t.profileId], foreignColumns: [adProfiles.orgId,adProfiles.id] }).onDelete('cascade')]);
export const adsCatalogueSourceCheckpoints = pgTable('ads_catalogue_source_checkpoints', { ...tenant, marketplaceId: text('marketplace_id').notNull(), family: text('family').notNull(), selectorKey: text('selector_key').notNull(), coveredFrom: ts('covered_from'), coveredThrough: ts('covered_through'), sourceObservedAt: ts('source_observed_at'), receiptId: uuid('receipt_id').references(() => adsCatalogueSourceReceipts.id), cursor: text('cursor'), cursorFailure: text('cursor_failure'), updatedAt: ts('updated_at').notNull() }, (t) => [primaryKey({ columns: [t.profileId,t.marketplaceId,t.family,t.selectorKey] }), foreignKey({ columns: [t.orgId,t.profileId], foreignColumns: [adProfiles.orgId,adProfiles.id] }).onDelete('cascade')]);
export const adsProductMetadataSnapshots = pgTable('ads_product_metadata_snapshots', { id: uuid('id').primaryKey(), ...tenant, marketplaceId: text('marketplace_id').notNull(), asin: text('asin').notNull(), sku: text('sku'), adProduct: adProduct('ad_product').notNull(), acquiredAt: ts('acquired_at').notNull(), retrievedAt: ts('retrieved_at').notNull(), providerObservedAt: ts('provider_observed_at'), contractVersion: text('contract_version').notNull(), snapshot: jsonb('snapshot').notNull(), payloadDigest: text('payload_digest').notNull(), receiptId: uuid('receipt_id').notNull().references(() => adsCatalogueSourceReceipts.id) }, (t) => [foreignKey({ columns: [t.orgId,t.profileId], foreignColumns: [adProfiles.orgId,adProfiles.id] }).onDelete('cascade'), index('ads_product_metadata_current_read').on(t.orgId,t.profileId,t.marketplaceId,t.asin,t.adProduct,t.acquiredAt)]);
export const adsProductEligibilitySnapshots = pgTable('ads_product_eligibility_snapshots', { id: uuid('id').primaryKey(), ...tenant, marketplaceId: text('marketplace_id').notNull(), asin: text('asin').notNull(), sku: text('sku'), adProduct: adProduct('ad_product').notNull(), verdict: text('verdict').notNull(), reasons: jsonb('reasons').notNull(), acquiredAt: ts('acquired_at').notNull(), retrievedAt: ts('retrieved_at').notNull(), providerObservedAt: ts('provider_observed_at'), contractVersion: text('contract_version').notNull(), payloadDigest: text('payload_digest').notNull(), receiptId: uuid('receipt_id').notNull().references(() => adsCatalogueSourceReceipts.id) }, (t) => [foreignKey({ columns: [t.orgId,t.profileId], foreignColumns: [adProfiles.orgId,adProfiles.id] }).onDelete('cascade'), index('ads_product_eligibility_current_read').on(t.orgId,t.profileId,t.marketplaceId,t.asin,t.adProduct,t.acquiredAt)]);
export const adsValidationConfigurations = pgTable('ads_validation_configurations', { id: uuid('id').primaryKey(), ...tenant, marketplaceId: text('marketplace_id').notNull(), resource: text('resource').notNull(), countryCode: text('country_code').notNull(), entityType: text('entity_type').notNull(), adProduct: adProduct('ad_product').notNull(), providerVersion: text('provider_version'), contentDigest: text('content_digest').notNull(), configuration: jsonb('configuration').notNull(), acquiredAt: ts('acquired_at').notNull(), retrievedAt: ts('retrieved_at').notNull(), receiptId: uuid('receipt_id').notNull().references(() => adsCatalogueSourceReceipts.id) }, (t) => [foreignKey({ columns: [t.orgId,t.profileId], foreignColumns: [adProfiles.orgId,adProfiles.id] }).onDelete('cascade'), uniqueIndex('ads_validation_configurations_identity').on(t.profileId,t.marketplaceId,t.resource,t.countryCode,t.entityType,t.adProduct,t.contentDigest)]);
export const amazonChangeEvents = pgTable('amazon_change_events', { id: uuid('id').primaryKey(), ...tenant, marketplaceId: text('marketplace_id').notNull(), sourceNamespace: text('source_namespace').notNull(), sourceEventKey: text('source_event_key').notNull(), identityQuality: text('identity_quality').notNull(), payloadDigest: text('payload_digest').notNull(), entityType: text('entity_type').notNull(), entityId: text('entity_id').notNull(), changeType: text('change_type').notNull(), occurredAt: ts('occurred_at').notNull(), retrievedAt: ts('retrieved_at').notNull(), sanitizedPayload: jsonb('sanitized_payload').notNull(), receiptId: uuid('receipt_id').notNull().references(() => adsCatalogueSourceReceipts.id) }, (t) => [foreignKey({ columns: [t.orgId,t.profileId], foreignColumns: [adProfiles.orgId,adProfiles.id] }).onDelete('cascade'), uniqueIndex('amazon_change_event_identity').on(t.profileId,t.marketplaceId,t.sourceNamespace,t.sourceEventKey,t.payloadDigest), index('amazon_change_events_timeline_read').on(t.orgId,t.profileId,t.occurredAt)]);
export const amazonChangeEventResolutions = pgTable('amazon_change_event_resolutions', { id: uuid('id').primaryKey(), ...tenant, eventId: uuid('event_id').notNull().references(() => amazonChangeEvents.id, { onDelete: 'cascade' }), resolvedEntityType: entityType('resolved_entity_type').notNull(), resolvedAmazonId: text('resolved_amazon_id').notNull(), resolvedAt: ts('resolved_at').notNull() }, (t) => [foreignKey({ columns: [t.orgId,t.profileId], foreignColumns: [adProfiles.orgId,adProfiles.id] }).onDelete('cascade'), uniqueIndex('amazon_change_resolution_identity').on(t.eventId,t.resolvedEntityType,t.resolvedAmazonId)]);

export const adsValidationConfigurationObservations = pgTable('ads_validation_configuration_observations', {
  id: uuid('id').primaryKey(), ...tenant, configurationId: uuid('configuration_id').notNull(), acquisitionKey:text('acquisition_key').notNull(),
  acquiredAt: ts('acquired_at').notNull(), retrievedAt: ts('retrieved_at').notNull(), providerObservedAt: ts('provider_observed_at'),
  contractVersion: text('contract_version').notNull(), receiptId: uuid('receipt_id').notNull(),
}, (t) => [uniqueIndex('ads_validation_observation_identity').on(t.configurationId,t.acquisitionKey),
  foreignKey({columns:[t.orgId,t.profileId,t.configurationId],foreignColumns:[adsValidationConfigurations.orgId,adsValidationConfigurations.profileId,adsValidationConfigurations.id]}),
  foreignKey({columns:[t.orgId,t.profileId,t.receiptId],foreignColumns:[adsCatalogueSourceReceipts.orgId,adsCatalogueSourceReceipts.profileId,adsCatalogueSourceReceipts.id]})]);
export const adsCatalogueAcquisitions = pgTable('ads_catalogue_acquisitions', {
  id: uuid('id').notNull(), ...tenant, marketplaceId: text('marketplace_id').notNull(), family:text('family').notNull(),
  selectorKey:text('selector_key').notNull(), requestFingerprint:text('request_fingerprint').notNull(),
  acquiredAt:ts('acquired_at').notNull(),windowStart:ts('window_start').notNull(),windowEnd:ts('window_end').notNull(),
  requestedMembers:integer('requested_members').notNull(),nextPosition:jsonb('next_position'),finalReceiptId:uuid('final_receipt_id'),
}, (t)=>[primaryKey({columns:[t.orgId,t.profileId,t.id]}),foreignKey({columns:[t.orgId,t.profileId],foreignColumns:[adProfiles.orgId,adProfiles.id]}).onDelete('cascade')]);
export const adsCataloguePages = pgTable('ads_catalogue_pages', {
  ...tenant,acquisitionId:uuid('acquisition_id').notNull(),pageNumber:integer('page_number').notNull(),expectedPosition:jsonb('expected_position').notNull(),
  nextPosition:jsonb('next_position'),pageFingerprint:text('page_fingerprint').notNull(),evidence:jsonb('evidence').notNull(),receiptId:uuid('receipt_id').notNull(),
}, (t)=>[primaryKey({columns:[t.orgId,t.profileId,t.acquisitionId,t.pageNumber]}),foreignKey({columns:[t.orgId,t.profileId,t.acquisitionId],foreignColumns:[adsCatalogueAcquisitions.orgId,adsCatalogueAcquisitions.profileId,adsCatalogueAcquisitions.id]}).onDelete('cascade')]);
