import { AdsApiParseError } from './errors.js';
import { isRecord } from './read.js';

export const PRODUCT_METADATA_PATH = '/product/metadata';
export const PRODUCT_METADATA_MEDIA = { request: 'application/vnd.productmetadatarequest.v1+json', response: 'application/vnd.productmetadataresponse.v1+json' } as const;
export const PRODUCT_ELIGIBILITY_PATH = '/eligibility/product/list';
export const VALIDATION_ENDPOINTS = {
  campaigns: { path: '/validationConfigurations/campaigns', mediaType: 'application/vnd.' + 'AdsApiValidationConfigsServiceLambda.' + 'CampaignsResource.v1+json', responseKey: 'campaignValidationConfigs' },
  targeting_clauses: { path: '/validationConfigurations/targetingClauses', mediaType: 'application/vnd.' + 'AdsApiValidationConfigsServiceLambda.' + 'TargetingClausesResource.v1+json', responseKey: 'targetingClausesValidationConfigs' },
} as const;
export const CHANGE_HISTORY_PATH = '/history';
export const CHANGE_HISTORY_ACCEPT = 'application/vnd.historyresponse.v1+json';
export const PRODUCT_METADATA_BATCH_SIZE = 300, PRODUCT_ELIGIBILITY_BATCH_SIZE = 50, CHANGE_HISTORY_PAGE_SIZE = 200;
export type CatalogueAdType = 'SP' | 'SB' | 'SD';
export interface ProductMetadataRequest { asins: readonly string[]; adType: CatalogueAdType; pageIndex?: number; cursorToken?: string | null }
export interface ProductMetadataRow { asin: string; sku: string | null; title: string | null; imageUrl: string | null; category: string | null; variationList: string[] | null; priceToPay: { amount: number; currency: string } | null; basisPrice: { amount: number; currency: string } | null; availability: string | null; bestSellerRank: number | null }
export interface ProductMetadataPage { rows: ProductMetadataRow[]; sourceRows: number; nextToken: string | null }
export interface ProductEligibilityRequest { asins: readonly string[]; adType: CatalogueAdType }
export interface ProductEligibilityRow { asin: string; sku: string | null; overallStatus: 'ELIGIBLE' | 'ELIGIBLE_WITH_WARNING' | 'INELIGIBLE'; reasons: Array<{ code: string; message: string | null; severity: string | null }> }
export interface ProductEligibilityResult { rows: ProductEligibilityRow[]; sourceRows: number; missingAsins: string[] }
export interface ValidationRequest { countryCodes: readonly string[]; entityTypes: readonly ('SELLER' | 'VENDOR')[]; adTypes: readonly CatalogueAdType[] }
export interface ValidationLeaf { countryCode: string; adType: CatalogueAdType; entityType: 'SELLER' | 'VENDOR'; configuration: Record<string, unknown> }
export interface ValidationResult { rows: ValidationLeaf[]; sourceRows: number }
export interface ChangeHistoryRequest { from: number; to: number; nextToken?: string | null }
export interface ChangeHistoryRow { entityType: 'AD' | 'AD_GROUP' | 'CAMPAIGN' | 'KEYWORD' | 'NEGATIVE_KEYWORD' | 'PRODUCT_TARGETING'; entityId: string; changeType: string; timestamp: number; previousValue: string | null; newValue: string | null; metadata: Record<string, string> }
export interface ChangeHistoryPage { rows: ChangeHistoryRow[]; sourceRows: number; nextToken: string | null }

function nonempty(value: unknown, name: string): string { if (typeof value !== 'string' || value.trim() === '') throw new AdsApiParseError(`${name} must be a non-empty string`); return value; }
const nullableString = (value: unknown): string | null => typeof value === 'string' ? value : null;
function money(value: unknown, name: string): { amount: number; currency: string } | null { if (value == null) return null; if (!isRecord(value) || typeof value['amount'] !== 'number' || !Number.isFinite(value['amount']) || typeof value['currency'] !== 'string') throw new AdsApiParseError(`${name} is malformed`); return { amount: value['amount'], currency: value['currency'] }; }
export function batchValues(values: readonly string[], size: number): string[][] { if (!Number.isSafeInteger(size) || size < 1) throw new RangeError('batch size must be positive'); if (new Set(values).size !== values.length) throw new AdsApiParseError('request contains duplicate identities'); const result: string[][] = []; for (let i = 0; i < values.length; i += size) result.push([...values.slice(i, i + size)]); return result; }
export function buildProductMetadataBody(request: ProductMetadataRequest) { if (request.asins.length < 1 || request.asins.length > 300) throw new AdsApiParseError('metadata ASIN batch must contain 1 through 300 values'); return { asins: [...request.asins], adType: request.adType, checkEligibility: false, checkItemDetails: true, pageIndex: request.pageIndex ?? 0, pageSize: 300, ...(request.cursorToken ? { cursorToken: request.cursorToken } : {}) }; }
export function parseProductMetadataPage(body: unknown): ProductMetadataPage {
  if (!isRecord(body) || !Array.isArray(body['ProductMetadataList'])) throw new AdsApiParseError('metadata response is missing ProductMetadataList[]');
  const rows = body['ProductMetadataList'].map((value, index): ProductMetadataRow => { if (!isRecord(value)) throw new AdsApiParseError(`metadata row ${index} is not an object`); const rawBsr = value['bestSellerRank']; const bestSellerRank = rawBsr == null ? null : Number(rawBsr); if (bestSellerRank !== null && (!Number.isFinite(bestSellerRank) || bestSellerRank < 0)) throw new AdsApiParseError(`metadata row ${index} has invalid bestSellerRank`); const variation = value['variationList']; if (variation !== undefined && (!Array.isArray(variation) || variation.some((v) => typeof v !== 'string'))) throw new AdsApiParseError(`metadata row ${index} has invalid variationList`); return { asin: nonempty(value['asin'], `metadata row ${index} asin`), sku: nullableString(value['sku']), title: nullableString(value['title']), imageUrl: nullableString(value['imageUrl']), category: nullableString(value['category']), variationList: variation === undefined ? null : variation as string[], priceToPay: money(value['priceToPay'], 'priceToPay'), basisPrice: money(value['basisPrice'], 'basisPrice'), availability: nullableString(value['availability']), bestSellerRank }; });
  return { rows, sourceRows: rows.length, nextToken: nullableString(body['cursorToken']) };
}
export function buildProductEligibilityBody(request: ProductEligibilityRequest) { if (request.asins.length < 1 || request.asins.length > 50) throw new AdsApiParseError('eligibility ASIN batch must contain 1 through 50 values'); return { adType: request.adType.toLowerCase(), productDetailsList: request.asins.map((asin) => ({ asin })) }; }
export function parseProductEligibility(body: unknown, requested: readonly string[]): ProductEligibilityResult {
  if (!isRecord(body) || !Array.isArray(body['productResponseList'])) throw new AdsApiParseError('eligibility response is missing productResponseList[]'); const requestedSet = new Set(requested), seen = new Set<string>();
  const rows = body['productResponseList'].map((value, index): ProductEligibilityRow => { if (!isRecord(value) || !isRecord(value['productDetails']) || !Array.isArray(value['eligibilityStatusList'])) throw new AdsApiParseError(`eligibility row ${index} is malformed`); const asin = nonempty(value['productDetails']['asin'], `eligibility row ${index} asin`); if (!requestedSet.has(asin)) throw new AdsApiParseError(`eligibility row ${index} was not requested`); seen.add(asin); const overallStatus = value['overallStatus']; if (!['ELIGIBLE','ELIGIBLE_WITH_WARNING','INELIGIBLE'].includes(String(overallStatus))) throw new AdsApiParseError(`eligibility row ${index} has invalid status`); const reasons = value['eligibilityStatusList'].map((reason, j) => { if (!isRecord(reason)) throw new AdsApiParseError(`eligibility reason ${j} is malformed`); return { code: nonempty(reason['name'], 'eligibility reason code'), message: nullableString(reason['message']), severity: nullableString(reason['severity']) }; }); return { asin, sku: nullableString(value['productDetails']['sku']), overallStatus: overallStatus as ProductEligibilityRow['overallStatus'], reasons }; });
  return { rows, sourceRows: rows.length, missingAsins: requested.filter((asin) => !seen.has(asin)) };
}
export function buildValidationBody(request: ValidationRequest) { if (request.countryCodes.length < 1 || request.countryCodes.length > 5 || request.entityTypes.length < 1 || request.entityTypes.length > 2 || request.adTypes.length < 1 || request.adTypes.length > 3) throw new AdsApiParseError('validation request must use explicit bounded contexts'); return { countryCodesList: [...request.countryCodes], entityTypesList: [...request.entityTypes], programTypesList: [...request.adTypes] }; }
export function parseValidation(body: unknown, resource: keyof typeof VALIDATION_ENDPOINTS, request: ValidationRequest): ValidationResult { const key = VALIDATION_ENDPOINTS[resource].responseKey; if (!isRecord(body) || !isRecord(body[key])) throw new AdsApiParseError(`validation response is missing ${key}`); const rows: ValidationLeaf[] = []; for (const countryCode of request.countryCodes) for (const adType of request.adTypes) for (const entityType of request.entityTypes) { const country = body[key][countryCode], program = isRecord(country) ? country[adType] : undefined, configuration = isRecord(program) ? program[entityType] : undefined; if (!isRecord(configuration)) throw new AdsApiParseError(`validation response omitted ${countryCode}/${adType}/${entityType}`); rows.push({ countryCode, adType, entityType, configuration }); } return { rows, sourceRows: rows.length }; }
export function buildChangeHistoryBody(request: ChangeHistoryRequest) { if (!Number.isSafeInteger(request.from) || !Number.isSafeInteger(request.to) || request.from >= request.to || request.to - request.from > 90 * 86400_000) throw new AdsApiParseError('history window must be increasing and at most 90 days'); const parent = { parents: [{ useProfileIdAdvertiser: true }] }; return { fromDate: request.from, toDate: request.to, count: 200, sort: { direction: 'ASC', key: 'DATE' }, eventTypes: { CAMPAIGN: parent, AD_GROUP: parent, AD: parent, KEYWORD: parent, NEGATIVE_KEYWORD: parent, PRODUCT_TARGETING: parent }, ...(request.nextToken ? { nextToken: request.nextToken } : {}) }; }
export function parseChangeHistoryPage(body: unknown): ChangeHistoryPage { if (!isRecord(body) || !Array.isArray(body['events'])) throw new AdsApiParseError('history response is missing events[]'); const rows = body['events'].map((value, index): ChangeHistoryRow => { if (!isRecord(value)) throw new AdsApiParseError(`history event ${index} is malformed`); const entityType = String(value['entityType']); if (!['AD','AD_GROUP','CAMPAIGN','KEYWORD','NEGATIVE_KEYWORD','PRODUCT_TARGETING'].includes(entityType) || !Number.isSafeInteger(value['timestamp'])) throw new AdsApiParseError(`history event ${index} has invalid identity or timestamp`); const metadata: Record<string,string> = {}; if (value['metadata'] !== undefined) { if (!isRecord(value['metadata'])) throw new AdsApiParseError(`history event ${index} metadata is malformed`); for (const [key,item] of Object.entries(value['metadata'])) if (typeof item === 'string') metadata[key] = item; } return { entityType: entityType as ChangeHistoryRow['entityType'], entityId: nonempty(value['entityId'], 'history entityId'), changeType: nonempty(value['changeType'], 'history changeType'), timestamp: value['timestamp'] as number, previousValue: nullableString(value['previousValue']), newValue: nullableString(value['newValue']), metadata }; }); return { rows, sourceRows: rows.length, nextToken: nullableString(body['nextToken']) }; }
